### ISSUE TITLE
Errors in health system capacity by state

### ISSUE THREAD

**Issue by UncleGedd** [covidcaremap/covid19-healthsystemcapacity#104]
Referring to https://github.com/covidcaremap/covid19-healthsystemcapacity/blob/master/data/published/us_healthcare_capacity-state-CovidCareMap.csv

Each state has population broken down by age 20+, 65+ and total, yet all these numbers are the same. I think this error influences the calculations for other columns as well.

**Comment by daveluo** [comment]
Thank you @UncleGedd  for catching this error! Will fix asap. The populations look broken out correctly at the county and HRR levels but we will double check all of them. Thanks again!
