### ISSUE TITLE
Develop visualization of healthcare system capacity.

### ISSUE THREAD

**Issue by lossyrob** [covidcaremap/covid19-healthsystemcapacity#11]
Generate a publicly-sharable visualization of the healthcare system capacity data being generated by this project.

There is a Kepler visualizaiton [here](hhttps://www.covidcaremap.org/viz/covid19-usabedcapacity-geoviz20200313v1) that is a starting point and uses the following datasets for visualization:
- [usa_hospital_beds_hcris2018_cleaned3 GeoJSON](https://github.com/daveluo/covid19-healthsystemcapacity/blob/master/data/usa_hospital_beds_hcris2018_cleaned3.geojson)
- [usa_county_hospital_bedcapacity2018 GeoJSON](https://github.com/daveluo/covid19-healthsystemcapacity/blob/master/data/usa_county_hospital_bedcapacity2018.geojson)

The latter is generated by [this notebook](https://github.com/daveluo/covid19-healthsystemcapacity/blob/master/nbs/usa_beds_capacity_analysis_20200313_v2.ipynb)

This includes communicating data needs that would improve or enhance the visualization effort. If new or different data would be useful, talk about it in the Gitter or write up an issue tagged with the `Data Request` label.

**Comment by Geoyi** [comment]
Find the link broken and fix. 
The Kepler visualization is now updated [here](https://www.covidcaremap.org/viz/covid19-usabedcapacity-geoviz20200313v1).

**Comment by lossyrob** [comment]
Thanks, updated description!

This was done as part of v0.1 release: https://www.covidcaremap.org/maps/us-healthcare-system-capacity
