### ISSUE TITLE
Compare your solution and data with mine (ManuelB/covid-19-vis)

### ISSUE THREAD

**Issue by ManuelB** [covidcaremap/covid19-healthsystemcapacity#116]
Hi guys,
awesome work. I did some similar stuff in my github repository:
 https://github.com/ManuelB/covid-19-vis/tree/gh-pages/simulation/usa

I am running an SIR model for every county in the USA. You can see a video here:
https://www.youtube.com/watch?v=uPYwL7mSI9w

I hope it is not that bad how I forecasted it in my evaluation.

/Manuel

**Comment by daveluo** [comment]
Hi @ManuelB, thanks for sharing! Quick q: it looks like you're using the SIR model from neherlab (https://neherlab.org/covid19/)? I may have missed this - could you please point to where in your repo you're keeping or feeding in the SIR modeling assumptions for the US by county?

**Comment by ManuelB** [comment]
Hi,
it is hard to find. It is here:  https://github.com/ManuelB/covid19_scenarios/blob/9e64c097bee46d7a53b301a24a5b9d317fab36fd/src/algorithms/run.test.tsx#L233

/Manuel
