### ISSUE TITLE
Prototype nbdev environment for module development in Jupyter notebooks

### ISSUE THREAD

**Issue by lossyrob** [covidcaremap/covid19-healthsystemcapacity#13]
We anticipate this project utilizing Jupyter notebooks heavily in development. In order to allow for notebook-driven development, while maintaining the ability to develop reusable code that can be imported by other notebooks or published as a package for use in other efforts, we should give https://nbdev.fast.ai/ a try. 

The goal of this issue is to test integrating nbdev (and potentially https://github.com/fastai/fastpages) into this project. This could take the form of a prototype set of notebooks that run inside the docker container and a set of scripts to compile the notebooks into a reusable library. The results of the exploration would best be documented clearly in this issue or perhaps as an ADR ([Architectural Decision Record](https://github.com/joelparkerhenderson/architecture_decision_record))

**Comment by lossyrob** [comment]
Note on this - the quickest route to common functionality is to introduce a small python package that extracts common code for notebook use as in #22. This may be the quickest path forward wrt sharing code that will be less overhead than introducing nbdev. However I think there is still value in exploring this route - I'm just less familiar with it and want to make sure it's clear the project may not go this direction unless there's strong indication that this will be useful and expedient for the project.

**Comment by daveluo** [comment]
I agree. Go with the tools and practices you know best to maximize our execution speed.

**Comment by lossyrob** [comment]
@hectcastro did an analysis on this and setup a prototype repo (https://github.com/hectcastro/healthsystemcapacity). Based on the conversation starting here: https://gitter.im/covid19-healthsystemcapacity/community?at=5e758514d5d28d3226603a3e, I agree with his recommendation and not using nbdev.
