### ISSUE TITLE
Get or create GeoJSON boundaries for different organizing levels (region, state, county, etc)

### ISSUE THREAD

**Issue by daveluo** [covidcaremap/covid19-healthsystemcapacity#16]
We're currently collecting and/or aggregating spatial data at the individual facility, county, and state levels. Based on feedback from health experts, capacity resourcing decisions could happen at those and other levels of organization like by city, township, hospital system's patient catchment area, or regional pandemic coordination team.

We should collect/create geoJSON files for the boundaries of these organizing areas and validate that they're correct and precise enough so that data can be cleanly aggregated, studied, and used to drive decisionmaking for officials working at those levels of jurisdiction and responsibility:

Must have:
-  [ ] all cities
-  [ ] all counties
-  [ ] all states

Should have:
-  [ ] all HHS regions: https://www.hhs.gov/about/agencies/iea/regional-offices/index.html
-  [ ] all CBSA: https://en.wikipedia.org/wiki/Core-based_statistical_area

Could be useful:
- local or regional pandemic coordination areas
- hospital referral regions and hospital service areas as defined by Dartmouth Atlas of Healthcare: https://www.dartmouthatlas.org/interactive-apps/medicare-reimbursements/
- hospital catchment areas more broadly defined or estimated: https://www.healthcare-economist.com/2010/11/23/defining-a-hospital-catchment-area/

**Comment by lossyrob** [comment]
Going with county, state, and HRR.
