### ISSUE TITLE
Downloading notebook is not avaliable

### ISSUE THREAD

**Issue by iamxiaodong** [covidcaremap/covid19-healthsystemcapacity#171]
Thanks for the efforts to put everything together, this is really amazing! I was trying to replicate the data preparation process from HCRIS, but realize that the downloading notebook is not available anymore. Could you please update the source so that I can take a look at? Thanks again for the amazing work!

**Comment by lossyrob** [comment]
Hi @iamxiaodong, thanks for the issue! The notebook actually exists here - https://github.com/covidcaremap/covid19-healthsystemcapacity/blob/master/notebooks/processing/00_Download_Data.ipynb - but I see that the link in the notebook README is broken.

Let us know if there's any other issues you run up against as you replicate the process!

**Comment by lossyrob** [comment]
Oh actually - the README link was correct. Can you let me know where you were searching for the download notebook and didn't find it? Thanks!

**Comment by iamxiaodong** [comment]
@lossyrob thanks for the response, I can access those notebooks now!
