### ISSUE TITLE
Map Viz Request: Vent supply and HGHI data by State

### ISSUE THREAD

**Issue by daveluo** [covidcaremap/covid19-healthsystemcapacity#40]
The outcome of an initial conversation with someone from the Harvard Global Health Institute work (referenced #33) is an urgent ask to map estimate of the ventilator supply by state from this 2010 paper: https://www.cambridge.org/core/journals/disaster-medicine-and-public-health-preparedness/article/mechanical-ventilators-in-us-acute-care-hospitals/F1FDBACA53531F2A150D6AD8E96F144D

I've copied table 4 into a spreadsheet and manually checked that the numbers* match up: https://docs.google.com/spreadsheets/d/1IDeFJJ1Kq5fXAp5vR_Fqp1jtf_4qjqqfeha5BsKUGe8/edit?usp=sharing

*Note that summing up the states + DC for columns B and D don't exactly add up to what's given as the US totals (off by 200 and -81 respectively) and this is the same in the original table. Not sure why  yet.

Given the urgency of the request (they're looking for something today or tomorrow so it can be used as a visual aid in their convos w/ decisionmakers), we can...

1. quickly create a geojson joining the vent supply with their state level data, already done at https://github.com/lossyrob/covid19-healthsystemcapacity/blob/rde/feature/hscap/data/hghi_state_data_with_vents.geojson

2. produce a quick web map with 2 layers (vent supply, HGHI data) from this geojson using kepler or leaflet. There may be some consideration about what data columns to show from each or a way to choose between columns to display but priority should be on speed of getting a basic map up.

3. host on repo or something that can be a direct weblink so it's easy to open/view/refer to

**Comment by mmcfarland** [comment]
I'm taking on this quick visualization and wanted to confirm my understanding of the desired outcome. I'm planning to do the following:

1. Create national scale web map using the state geographies in the referenced geojson file above
2. Use a default attribute (one of the ventilator attributes, likely) as the default layer.
3. The attribute layer will be a [choropleth map ](https://en.wikipedia.org/wiki/Choropleth_map) visualizing the attribute value for that state.
4. Click on a state to view all state values
5. Optionally, allow the user to select other attributes in the dataset as the visualization layer.

Outstanding question from me: if this assessment is correct, can I get input into what class breaks or categorizations to use for any of the high priority layer values? For example, in the simplest form, we could have values categorized as "low", "med", "high" (or similar terminology). What value ranges would belong to each category. Related, are there color ramps that are desired to use for these class breaks?

If a differently type of visualization would be more effective, please let me know.
  Optionally, we give the user the option to select which attribute to use on the current layer. We need a

**Comment by daveluo** [comment]
Thanks @mmcfarland for laying out your understanding. Comments in-line:

> 1. Create national scale web map using the state geographies in the referenced geojson file above

Correct

> 2. Use a default attribute (one of the ventilator attributes, likely) as the default layer.

Correct. We can default to the `Estimated No. Full-Featured Mechanical Ventilators per 100,000 Population` attribute.

> 3. The attribute layer will be a choropleth map visualizing the attribute value for that state.

Correct and I think the above per capita numbers for total vent supply would make the most sense as a chloropleth that visually compares across states adjusted for population

> 4. Click on a state to view all state values

Correct

> 5. Optionally, allow the user to select other attributes in the dataset as the visualization layer.

If this isn't much more work, yes that would be great!

I'm thinking about the class breaks now and will follow up in another comment

**Comment by daveluo** [comment]
Here are some sources for inspiration on color ramp and other viz design choices already made on this dataset (i'm not a designer by any means so I have very bad intuition about these things): 

https://www.nytimes.com/interactive/2020/03/17/upshot/hospital-bed-shortages-coronavirus.html
https://projects.propublica.org/graphics/covid-hospitals

The issue is that both of those media sources chose to look at % exceeded over some capacity which is not as relevant to what we need right now.

The main thing we are trying to communicate is how many ventilators there are and where they're distributed spatially (either normalized to population or not). The next thing I would want to compare this vent count against is the total number or per capita number of available and potentially available ICU beds now and estimated need in the future based on their scenarios (this corresponds to the "6 months", "12 mos", "18 mos"). The interplay of these two is what constraints the ability to provide ICU care at a state by state level.

I don't know if that helps you figure out what the class breaks should be but the high priority attributes that should be visualize-able (if providing the ability to select from a few) include:

- Estimated No. Full-Featured Mechanical Ventilators 
- Estimated No. Full-Featured Mechanical Ventilators per 100,000 Population
- Total ICU Beds
- Available ICU Beds 
- Potentially Available ICU Beds*
- ICU Beds Needed, Six Months
- ICU Beds Needed, Twelve Months
- ICU Beds Needed, Eighteen Months

I also just noticed their HGHI data doesn't have columns for ICU beds per capita (by 100,000 population lets say) so I can calculate these columns if you're planning to use them.

**Comment by lossyrob** [comment]
Closed by #41
