### ISSUE TITLE
Broken link on website

### ISSUE THREAD

**Issue by jfrankl** [covidcaremap/covid19-healthsystemcapacity#50]
The https://www.covidcaremap.org/#data section references https://www.covidcaremap.org/data/published/ but that seems to be a broken link.

**Comment by daveluo** [comment]
This seems to be an issue with github pages linking with the README as the index page. I've temporarily made it an absolute link to https://github.com/covidcaremap/covid19-healthsystemcapacity/tree/master/data/published 

As noted in Rob's PR comment (https://github.com/covidcaremap/covid19-healthsystemcapacity/pull/61#pullrequestreview-380000484), this would always point to master, not the tagged version as we're intending:


This should be resolved once we move the project site off rendering directly from the README
