### ISSUE TITLE
Improve Deployment

### ISSUE THREAD

**Issue by lossyrob** [covidcaremap/covid19-healthsystemcapacity#73]
The goal of this issue is to establish a better deployment story for covidcaremap.org.

Things that we need:
- Staging/production: A deployment scenario that let us test on a staging environment to make sure everything looks legit before pushing to production.
- CI: Build and deploy static asset webpages to staging.

### What we're doing now
Currently we are hosting all data on GitHub under the `data/` folder. I think this continues to make sense to host the latest data. However for published data we may want to host that somewhere else and only push the new data when we push to production. This will allow us validate the data more easily and collaboratively in the repo and on staging before pushing it out to the world.

The two maps we have are under `viz/`. One is a pure static vanilla javascript (https://www.covidcaremap.org/maps/us-healthcare-system-capacity), and the other is a react application that requires an npm build (https://www.covidcaremap.org/maps/hghi-vents/). The current process is to run the `docker/generate-maps` command to move all the built static assets into the `maps/` directory, commit that, and then that becomes the published versions of the sites on GitHub pages.

There is some data processing in a notebook [here](https://github.com/covidcaremap/covid19-healthsystemcapacity/blob/master/notebooks/processing/07_Process_visualization_data.ipynb) that runs tippecanoe and moves some of the data from `data/` into places where the UI uses them. This can be modified as needed to be part of a CI process.

The current main covidcaremap.org site is just a rendering of our README.md via GitHub pages. @jfrankl is working on a new design for the site that will be it's own Jekyll project - unclear if that should be inside this repository or in a new repository. One consideration is that if we still use GH Pages to host the main site, but use some other hosting mechanism to host the static assets for the maps, we'd have to route things correctly so that `covidcaremap.org` and covidcaremap.org/maps/...` would still work out.

**Comment by dmfenton** [comment]
I think we should separate the data from the website. Create a separate pipeline that generates the vector tiles and pushes the tiles and other data to an s3 bucket. Then the website can point to a CloudFront distribution fronting that bucket. I have the AWS portion of this ready to go including a service account for CI to use. Travis-CI and Github Actions both seem like good candidates for the CI.

For the website, use netlify, zeit, gh-pages or whatever else works. I don't have a really strong opinion here though I think free options are preferable.

**Comment by lossyrob** [comment]
Conversation on Gitter about the pros/cons of refactoring to support data processing/serving in a different pipeline than the webpage deploy through netlify:

https://gitter.im/covid19-healthsystemcapacity/community?at=5e7cb1efbf65703264dd9963
https://gitter.im/covid19-healthsystemcapacity/community?at=5e7cc6aea73c1910996c1222
