### ISSUE TITLE
Add PR instructions to README

### ISSUE THREAD

**Issue by lossyrob** [covidcaremap/covid19-healthsystemcapacity#98]
Add instructions on how to use GitHub forks to make a PR to this repository, as there have been a few questions around that. Should probably go in CONTRIBUTING.md and can be a resource to point to as the question comes up.

**Comment by AndyMc629** [comment]
Hi, noticed there is a PR section in the contributing.md file now, do you want this updated/made more clear for people or should this issue now be closed?

**Comment by lossyrob** [comment]
Good call, thanks @AndyMc629 !
